---
#
# We  assume here  that  *.localhost resolves  to  the local  machine.
# Following URL should be directed to corresponding Service, also with
# https:// protocoll:
#
#     http://llama.localhost
#
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "llama-server"
spec:
  rules:
  - host: "llama-server.localhost"
    http:
      paths:
      - path: "/"
        pathType: "Prefix"
        backend:
          service:
            name: "llama-server"
            port:
              number: 80
---
# https://github.com/rancher/local-path-provisioner
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llama-models
spec:
  accessModes:
    - ReadWriteOnce
  # When you  dont specify  storage class at  all the  default storage
  # class may be chosen. In k3s with local-path provisioner it is also
  # the  default one.  Omitted  storageClassName is  not  the same  as
  # storageClassName = "".
  # storageClassName: local-path
  resources:
    requests:
      storage: 4Gi
...
